# -------------------------------------------------------------
# User settings for data files and gene label
# -------------------------------------------------------------
# User settings for data files and gene label

# -------------------------------------------------------------
# Mammalian REV3L
# -------------------------------------------------------------
Nucleotide: data/mammalian_REV3L/REV3L_refseq_transcript.fasta
Protein: data/mammalian_REV3L/YYBZHZKX212-alignment.fa
CSV: data/mammalian_REV3L/REV3L_orthologs.csv
Label: mammalian_REV3L
TN93_Threshold: 0.1

# User settings for NCBI Entrez
EMAIL: ""

# -------------------------------------------------------------
# Do not change below this line
# -------------------------------------------------------------

PREMSA: hyphy-analyses/codon-msa/pre-msa.bf
POSTMSA: hyphy-analyses/codon-msa/post-msa.bf
FMM: hyphy-analyses/FitMultiModel/FitMultiModel.bf
BUSTEDSMH: hyphy-analyses/BUSTED-MH/BUSTED-MH.bf
FITMG94: hyphy-analyses/FitMG94/FitMG94.bf
HYPHY: hyphy
HYPHYMPI: HYPHYMPI
STRIKEAMBIGS: scripts/strike-ambigs.bf

# -------------------------------------------------------------
# End of file
# -------------------------------------------------------------
