# User settings for data files and gene label

# Primate ACE2
Nucleotide: ACE2_refseq_transcript.fasta
Protein: ACE2_refseq_protein.fasta
CSV: ACE2_orthologs.csv
Label: PrimateACE2

# Vertebrate BTG1
#Nucleotide: BTG1_refseq_transcript.fasta
#Protein: BTG1_refseq_protein.fasta
#CSV: BTG1_orthologs.csv
#Label: VertebrateBTG1

# Mammalian BTG1
#Nucleotide: BTG1_refseq_transcript.fasta
#Protein: BTG1_refseq_protein.fasta
#CSV: BTG1_orthologs.csv
#Label: MammalianBTG1

# Mammalian BCL6
#Nucleotide: BCL6_refseq_transcript.fasta
#Protein: BCL6_refseq_protein.fasta
#CSV: BCL6_orthologs.csv
#Label: MammalianBCL6

# Primate BTG1
#Nucleotide: BTG1_refseq_transcript.fasta
#Protein: BTG1_refseq_protein.fasta
#CSV: BTG1_orthologs.csv
#Label: PrimateBTG1

# User settings for NCBI Entrez
Email: "agl4001@med.cornel..edu"
